### ISSUE TITLE
ハード監視が通知されない

### ISSUE THREAD

**Issue by lucida3rd** [lucida3rd/lucibot#14]
とてもチープな問題だと思われる。

Traceback (most recent call last):
  File "_sub.py", line 32, in <module>
    CLS_BOT_Sub.sRun()	#起動
  File "script/bot_sub.py", line 180, in sRun
    wOBJ_LookHard = CLS_LookHard( parentObj=cls )
  File "script/func/lookhard.py", line 51, in __init__
    self.__run()	#処理開始
  File "script/func/lookhard.py", line 93, in __run
    self.Hard_Info()
  File "script/func/lookhard.py", line 227, in Hard_Info
    wRunDate = wRuntime['BootTD'].split(" ")
KeyError: 'BootTD'

**Comment by lucida3rd** [comment]
v4.1.0.1で修正済。クローズとする。
