### ISSUE TITLE
DB初期化直後、品詞パターンがない状態で例外となる

### ISSUE THREAD

**Issue by lucida3rd** [lucida3rd/lucibot#18]
エラーログ＞
Traceback (most recent call last):
  File "_master.py", line 32, in <module>
    CLS_BOT_Master.sRun()	#起動
  File "script/bot_master.py", line 205, in sRun
    wOBJ_RandToot = CLS_RandToot( parentObj=cls )
  File "script/func/randtoot.py", line 58, in __init__
    self.__run()	#処理開始
  File "script/func/randtoot.py", line 87, in __run
    wCHR_Toot = self.Obj_Parent.OBJ_WordCorr.GetRandToot()
  File "script/func/wordcorr.py", line 138, in GetRandToot
    self.Obj_Parent.OBJ_Mylog.Log( 'a', "CLS_WordCorr: GetRandToot: Run Query is failed (get TBL_CLAZ_LIST is not 1): " + wDBRes['Reason'] + " query=" + wDBRes['Query'] )
TypeError: can only concatenate str (not "NoneType") to str

L138のログ出しで、タイプエラーになっている。
よく分からないので、詳細調査の必要あり。

**Comment by lucida3rd** [comment]
Statusにない要素を表示しようとしてコケてたみたい。
v4.1.0.8で修正済。クローズとする。
